debian/icedove.desktop usr/share/applications

debian/tmp/usr/lib/icedove/lib*
debian/tmp/usr/lib/icedove/*.ini
debian/tmp/usr/lib/icedove/blocklist.xml
debian/tmp/usr/lib/icedove/defaults/pref usr/share/icedove/defaults
debian/tmp/usr/lib/icedove/defaults/messenger usr/share/icedove/defaults
debian/tmp/usr/lib/icedove/extensions/\{972ce4c6-7e08-4474-a285-3208198ce6fd\} usr/share/icedove/extensions
debian/tmp/usr/lib/icedove/isp usr/share/icedove
debian/tmp/usr/lib/icedove/icedove*
debian/tmp/usr/lib/icedove/chrome usr/share/icedove
debian/tmp/usr/lib/icedove/run-mozilla.sh
debian/tmp/usr/lib/icedove/mozilla-xremote-client
debian/tmp/usr/lib/icedove/plugin-container
debian/tmp/usr/lib/icedove/removed-files
debian/tmp/usr/lib/icedove/omni.ja usr/share/icedove
debian/tmp/usr/lib/icedove/searchplugins usr/share/icedove
debian/tmp/usr/lib/icedove/dependentlibs.list

debian/tmp/usr/lib/icedove/components/*
debian/tmp/usr/lib/icedove/chrome.manifest

debian/icedove.js etc/icedove/pref
debian/vendor.js usr/share/icedove/defaults/pref

debian/account-autoconfig/* usr/share/icedove/isp
