#!/bin/sh

set -e

LIBDIR=/usr/lib/thunderbird

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] ; then
    touch $LIBDIR/.autoreg
fi

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt "3.0.4-3" && [ -e /etc/icedove/messenger/mailViews.dat ]; then
    MD5=`md5sum /etc/icedove/messenger/mailViews.dat|cut -d ' ' -f1`
    if [ "$MD5" = "79fc655e9dd95c30ae52cc230c5aaa30" ]; then
        rm /etc/icedove/messenger/mailViews.dat
        rmdir /etc/icedove/messenger || true
    fi
fi

dpkg-maintscript-helper rm_conffile /etc/icedove/profile/US/localstore.rdf "5.0-1" -- "$@"
dpkg-maintscript-helper rm_conffile /etc/icedove/profile/US/mimeTypes.rdf "5.0-1" -- "$@"
dpkg-maintscript-helper rm_conffile /etc/icedove/profile/prefs.js "5.0-1" -- "$@"
dpkg-maintscript-helper rm_conffile /etc/icedove/profile/mimeTypes.rdf "5.0-1" -- "$@"
dpkg-maintscript-helper rm_conffile /etc/icedove/profile/localstore.rdf "5.0-1" -- "$@"

#DEBHELPER#
