#!/bin/sh

set -e

# transpose directory into symlink
symlink_dir() {
    LNSOURCE=$1
    DIR=$2
    if [ ! -L $DIR ]; then
        rmdir $DIR
        ln -s $LNSOURCE $DIR
    fi
}

if [ "$1" = "configure" ] && dpkg --compare-versions "$2" lt "1:3.1.9-2"; then
    symlink_dir "/usr/share/icedove/extensions/langpack-fr@thunderbird.mozilla.org" \
                "/usr/lib/icedove/extensions/langpack-fr@thunderbird.mozilla.org"
fi

#DEBHELPER#
