debian/account-autoconfig/*                       usr/share/thunderbird/isp
debian/thunderbird.desktop                        usr/share/applications
debian/thunderbird.js                             etc/thunderbird/pref
debian/tmp/usr/lib/thunderbird/*.ini
debian/tmp/usr/lib/thunderbird/blocklist.xml
debian/tmp/usr/lib/thunderbird/chrome             usr/share/thunderbird
debian/tmp/usr/lib/thunderbird/defaults/messenger usr/share/thunderbird/defaults
debian/tmp/usr/lib/thunderbird/defaults/pref      usr/share/thunderbird/defaults
debian/tmp/usr/lib/thunderbird/dependentlibs.list
debian/tmp/usr/lib/thunderbird/thunderbird*
debian/tmp/usr/lib/thunderbird/isp                usr/share/thunderbird
debian/tmp/usr/lib/thunderbird/lib*
debian/tmp/usr/lib/thunderbird/omni.ja            usr/share/thunderbird
debian/tmp/usr/lib/thunderbird/plugin-container
debian/tmp/usr/lib/thunderbird/removed-files
debian/tmp/usr/lib/thunderbird/run-mozilla.sh
debian/vendor.js                                  usr/share/thunderbird/defaults/pref
